"""
Django settings for Property_Renting_Application project.

Generated by 'django-admin startproject' using Django 1.11.20.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os,sys
from dotenv import load_dotenv
from unipath import Path

PROJECT_DIR = Path(__file__).ancestor(3)
PROJECT_APPS = Path(__file__).ancestor(2)

sys.path.insert(0,Path(PROJECT_APPS,'apps'))
load_dotenv(os.path.join(PROJECT_DIR, '.env'))


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'w*3-xr$ly2r%iy!v!g98l&mx-71y^23b-o(^bdu_l6w$3y^(8!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social_django',
    'property',
    'users',
    'widget_tweaks',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'social_django.middleware.SocialAuthExceptionMiddleware',
]

AUTHENTICATION_BACKENDS = [
    'social_core.backends.linkedin.LinkedinOAuth2',
    'social_core.backends.google.GoogleOAuth2',
    'social_core.backends.instagram.InstagramOAuth2',
    'social_core.backends.github.GithubOAuth2',
    'social_core.backends.facebook.FacebookOAuth2',
    'django.contrib.auth.backends.ModelBackend',
]

SOCIAL_AUTH_FACEBOOK_KEY = "507662179903915"        # App ID
SOCIAL_AUTH_FACEBOOK_SECRET = "38010f5f2d4759ce3afe665738217f5d"  # App Secret

SOCIAL_AUTH_GITHUB_KEY = "f8619745b4a59217ee12"        # App ID
SOCIAL_AUTH_GITHUB_SECRET = "ebd4069f6c619274bae58ee45eb4793568208546"  # App Secret

SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY = "818nhhpyjsjk52"         #Client ID
SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET = "vVl73byWfCM1gRM9" 


SOCIAL_AUTH_GOOGLE_OAUTH2_KEY ="614696473560-e4jn6g31i5uum04dgh221d54hmceeo7e.apps.googleusercontent.com"
SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET = "e6W5F8hf_sL2XkIwS9pANyvR"

SOCIAL_AUTH_INSTAGRAM_KEY = "364956607772871"         #Client ID
SOCIAL_AUTH_INSTAGRAM_SECRET = "186f25642b18a09c766dde9a8d18a8cf"
# SOCIAL_AUTH_INSTAGRAM_EXTRA_DATA = [  ('user', 'user'),]
SOCIAL_AUTH_INSTAGRAM_AUTH_EXTRA_ARGUMENTS = {'scope': 'user_profile,user_media'}

# SOCIAL_AUTH_LOGIN_REDIRECT_URL = 'http://localhost:8000/'
SOCIAL_AUTH_INSTAGRAM_REDIRECT_URI = 'https://92a0c747.ngrok.io/oauth/complete/instagram/'
ROOT_URLCONF = 'Property_Renting_Application.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [PROJECT_APPS.child("templates"),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            
                'social_django.context_processors.backends',  # <--
                'social_django.context_processors.login_redirect',

            ],
        },
    },
]

WSGI_APPLICATION = 'Property_Renting_Application.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/


MEDIA_ROOT = PROJECT_APPS.child('media')

MEDIA_URL = '/media/'

# Static files (CSS, JavaScript, Images, Pdf)
STATIC_ROOT = PROJECT_APPS.child('staticfiles')

STATIC_URL = '/staticfiles/'

STATICFILES_DIRS = [
   PROJECT_APPS.child("static"),
]    

LOGIN_REDIRECT_URL = '/'                          
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
os.path.join(BASE_DIR, "static"),
]
STATIC_URL = '/static/'


DATABASES = {
    'default': {
        'ENGINE':   'django.db.backends.postgresql',
        'NAME':     'property_renter',
        'USER':     'postgres',
        'PASSWORD': 'psql',
        'HOST':     'localhost',
        'PORT':     5432,
    }
}





DEFAULT_FROM_EMAIL = 'property@gmail.com'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.sendgrid.net'
EMAIL_HOST_USER = 'apikey'
EMAIL_HOST_PASSWORD = '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'
EMAIL_PORT = 587


