# Generated by Django 3.0 on 2020-04-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0002_auto_20200402_0717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_img',
            field=models.ImageField(blank=True, null=True, upload_to='pic_folder'),
        ),
    ]
