# Generated by Django 3.0.2 on 2020-04-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20200414_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='type_of_property',
            field=models.CharField(blank=True, choices=[('Rent', 'For Rent'), ('Sale', 'For Sale')], max_length=4, null=True),
        ),
    ]
