# Generated by Django 3.0.2 on 2020-04-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0009_property_type_of_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='property',
            name='prize',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='size',
            field=models.IntegerField(),
        ),
    ]
