# Generated by Django 3.0.2 on 2020-04-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20200415_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_img',
            field=models.ImageField( upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='type_of_property',
            field=models.CharField(choices=[('Rent', 'For Rent'), ('Sale', 'For Sale')], max_length=4),
            preserve_default=False,
        ),
    ]
