# Generated by Django 3.0.2 on 2020-05-05 16:59

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_auto_20200415_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
